# Generated by Django 4.1 on 2022-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhoAmI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("about", models.TextField(blank=True)),
                ("age", models.IntegerField()),
                ("number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("photo", models.FileField(upload_to="media/%Y/%m/%d")),
                ("github", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
