# Generated by Django 4.0.4 on 2022-08-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whoami',
            options={'verbose_name_plural': 'WhoAmI'},
        ),
    ]
