# Generated by Django 4.1 on 2022-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_whoami_options"),
    ]

    operations = [
        migrations.DeleteModel(name="WhoAmI",),
    ]
